### ISSUE TITLE
missing babel-runtime?

### ISSUE THREAD

**Issue by aredridel** [millermedeiros/esformatter#424]
When I upgrade from 0.8 to 0.9.3, I get this when I try to run esformatter:

```
:; esformatter
module.js:341
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/interop-export-wildcard'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/aredridel/Projects/npm/npm-website/node_modules/babel-types/lib/index.js:13:30)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by millermedeiros** [comment]
that's weird, I was not able to reproduce this. can you try `npm cache clean esformatter babel-runtime` and install `esformatter` again?

**Comment by millermedeiros** [comment]
can't repro and nobody else reported this, so I'm going to close it as invalid.

PS: I'm also going to change the way the parser is loaded soon, so it might actually help to solve this issue (#440)

**Comment by aredridel** [comment]
Alright. might also have been an npm bug in one of the older 3.x series.
